import mongoose from "mongoose";

const salesReportSchema = new mongoose.Schema(
  {
    // Report metadata
    period: {
      type: String,
      enum: ["daily", "weekly", "monthly"],
      required: true,
    },
    reportDate: {
      type: Date,
      required: true,
      index: true,
    },

    // Summary metrics
    totalOrders: {
      type: Number,
      default: 0,
    },
    totalRevenue: {
      type: Number,
      default: 0,
    },
    ordersDelivered: {
      type: Number,
      default: 0,
    },
    ordersPending: {
      type: Number,
      default: 0,
    },
    ordersFailed: {
      type: Number,
      default: 0,
    },
    ordersShipped: {
      type: Number,
      default: 0,
    },

    // Averages
    averageOrderValue: {
      type: Number,
      default: 0,
    },
    averageDeliveryTime: {
      type: Number, // in hours
      default: 0,
    },
    successRate: {
      type: Number, // percentage
      default: 0,
    },

    // Delivery boy performance
    deliveryBoySales: [
      {
        deliveryBoyId: mongoose.Schema.Types.ObjectId,
        deliveryBoyName: String,
        ordersAssigned: Number,
        ordersDelivered: Number,
        ordersFailed: Number,
        revenue: Number,
        successRate: Number,
      },
    ],

    // Top products (from API)
    topProducts: [
      {
        productId: String,
        productName: String,
        unitsSold: Number,
        revenue: Number,
      },
    ],

    // Customer insights
    newCustomers: Number,
    returningCustomers: Number,
    averageCustomerOrderValue: Number,

    // Generated by
    generatedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
    },
  },
  { timestamps: true }
);

// Create index for efficient queries
salesReportSchema.index({ period: 1, reportDate: -1 });

const SalesReport = mongoose.model("SalesReport", salesReportSchema);

export default SalesReport;
